### ISSUE TITLE
Tooltip is disrupted at a high zoom level

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-supporting-documents-redesign#13]
### Steps to reproduce

1. Use a common screen resolution for a desktop computer. My physical screen is 1366x768. (This issue might also be reproducible in landscape tablet.)
2. Browse the web page. https://w3c.github.io/wai-wcag-supporting-documents-redesign/2020-07-15-prototype.html
3. Zoom the browser not all the way to the mobile breakpoint, but only to around 455px width. In my Chromebook browser this occurs at 300% browser zoom.
4. Observe the "i" icon for "All supporting documents".
5. Hover the mouse pointer on the "i" icon.

### Actual result

At step 4, the "i" icon is visually dissociated from the "All supporting documents" that it should describe.

At step 5, the tooltip text extends above the top of the document and cannot be scrolled into view.

![Screenshot showing the issues at steps 4 and 5](https://user-images.githubusercontent.com/3124805/89722208-30587e00-d9e7-11ea-8b7b-c3994b831f33.png)

### Expected result

At step 4, the "i" icon should be visually associated with the "All supporting documents" text that it describes.

At step 5, the tooltip flyout should be positioned in a way that allows scrolling the tooltip text into view.

**Comment by hidde** [comment]
Thanks also for this comprehensive report; am closing the issue as we're removing tooltips from the project entirely, but let's keep all this in mind should we plan to add tooltips.
