### ISSUE TITLE
Difficult to scroll some aside text into view

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-supporting-documents-redesign#14]
### Steps to reproduce

1. Use a somewhat smaller screen resolution for a desktop computer, such as 1024x768, or use browser zoom.
2. Browse the web page. https://w3c.github.io/wai-wcag-supporting-documents-redesign/2020-07-15-prototype.html
3. Visually read the content of the aside element (the right-hand sidebar). When the text is taller than the viewport, scroll down to read it.

### Actual result

In the following screenshot, the document is scrolled about one third of the way down. The "Other sources" text in the aside element has not scrolled into view (it remains in a "sticky" or fixed position below the bottom edge of the viewport).

![Screenshot of 'actual result' described above](https://user-images.githubusercontent.com/3124805/89722410-c2fa1c80-d9e9-11ea-8542-8700b5078ce9.png)

Workaround: Scroll down about 90-95% through the whole document, and the rest of the aside text comes into view. It scrolls out of view again at 100% scroll position.

### Expected result

Personally I find the "sticky" behavior of this aside element more distracting than useful. When I'm scrolling down, I would prefer to focus my visual attention on the main body content without the distraction of the aside element following me. This would also fix the current issue.

Alternately, think of a different design change to fix the described issue.

**Comment by hidde** [comment]
Many thanks for the feedback, @mitchellevan. The sticky behavior has been removed, to avoid this problem and others.
