### ISSUE TITLE
Tooltip balloon is not dismissed by keyboard and has counterintuitive mouse dismissal

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-supporting-documents-redesign#15]
### Steps to reproduce

Seen in Chrome browser.

1. Browse the web page. https://w3c.github.io/wai-wcag-supporting-documents-redesign/2020-07-15-prototype.html
2. Tab to an "i" icon. Note that the tooltip balloon appears when the "i" icon receives focus, and the tooltip balloon covers other content in the page.
3. While focus is on the "i" icon, attempt to use the keyboard to dismiss the tooltip balloon without moving focus, such as by pressing Enter or Escape.
4. Tab forward to a link (if present) inside the tooltip balloon.
5. Tab forward to content outside of the tooltip balloon.
6. Refresh the page.
7. Hover the mouse pointer over the "i" icon. Note that the tooltip balloon appears.
8. Press the mouse button to click the "i" icon.
9. Press the mouse button to click the "i" icon a second time.
 
### Actual behavior

At step 3, there is no keyboard mechanism to hide the tooltip balloon. This fails the "Dismissible" requirement of WCAG 1.4.13 Content on Hover or Focus.

If the tooltip balloon contained a link in step 4, then at step 5 the tooltip balloon remains on the screen covering other content. Screenshot:
![Screenshot of the step 5 issue occurring on the 'All supporting documents' tooltip](https://user-images.githubusercontent.com/3124805/89722906-a6f97980-d9ef-11ea-88bf-b08fe0a03fe9.png)

At step 8, the tooltip balloon disappears, and at step 9 the tooltip balloon remains invisible. This is counterintuitive because on other websites, clicking often causes tooltip balloons to appear.

### Expected behavior

My suggestion: show the contextual help information only on click activation of the "i" icon, not on hover or focus.

**Comment by hidde** [comment]
Thanks for the comprehensive bug report. In the latest versions, we're no longer using the tooltip so am closing this issue, but keeping in mind to revisit should we ever readd tooltips.
