### ISSUE TITLE
visual design - W3C TR or WAI site?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-supporting-documents-redesign#2]
For some people, W3C TR* has established weight and credibility of W3C Standards ("Recommendations") and Working Group Notes. Is that a reason to use the TR visual design, outweighing reasons to use the WAI visual design?

_(Personally, I mildly think probably not, and welcome other perspectives to help shape my thinking on this issue.)_

*"TR" is the URI for W3C standards, such as https://www.w3.org/TR/WCAG/ (it comes from "technical report")

**Comment by hidde** [comment]
Closing this issue, as it seems to me there is enough consensus for using WAI visual design (cc @nitedog).

**Comment by hidde** [comment]
I forgot to actually close it as per the above comment.
