### ISSUE TITLE
Do we want to display first SC in GL in the prev/next component?

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-supporting-documents-redesign#28]
## Description

In Understanding documents, we're adapting the previous / next component from the WAI website, to allow people to browse from one Guideline / SC to the next. (Following EOWG feedback that this is useful for Understanding docs, but not for Techniques)

In the current Understanding document (see [Understanding 1.3](https://www.w3.org/WAI/WCAG21/Understanding/adaptable)), a link is available to the first SC within  an SC:

<img width="1268" alt="at top of understanding doc, four button-like links appear: to contents, to previous guideline, to first sc (with pink circle drawn around), to next guideline" src="https://user-images.githubusercontent.com/178782/100727136-23143480-33c6-11eb-80f5-3c278dbc0de0.png">

In the redesign, we're reusing the previous/next component from the WAI website. This is what it looks like (see [Draft redesign for Understanding 1.3](https://draft-wcag-redesign.netlify.app/understanding/adaptable)):

<img width="984" alt="the previous next component like on the WAI site with links to previous guideline, next guideline and first sc underneath " src="https://user-images.githubusercontent.com/178782/100727890-1e9c4b80-33c7-11eb-8f0b-5a46ac3cc0d8.png">

Given that: 

* It seems trying to link to the first SC there would make the previous/next idea less focused. 
* A link to the first SC (and all SCs within the Guideline) is available in the section just above

## Proposal 

Let's not have a link to the first SC in the previous/next component for a Guideline. 

cc @slhenry @nitedog 

<details>
<summary>Related: solution for link to Guideline from SC</summary>
<img width="985" alt="previous next component with link to previous and next sc, with at the top with a different background color a link to the guideline it belongs to" src="https://user-images.githubusercontent.com/178782/100728055-5905e880-33c7-11eb-99ef-fe3564fa0268.png">
</details>

**Comment by slhenry** [comment]
I appreciate wanting to re-use the existing component. I do think we probably want to expand it for the Understanding docs. It was designed for resources with one level of hierarchy and a few pages -- where we hoped readers would read the entire resource. The Understanding docs have 2 levels and lots of page with lots of info on each page -- and probably people won't read through all of a page, then go to the next one, then read all of a page, then go to the next one, etc.

It'd be good to jot down some user workflows -- then decide which ones have priority for the UI. For example:

User Scenario 1:
* I'm wanting to understand the media requirements, so I'm walking through those SCs. I'm mostly skimming the Intent and sometimes the examples, then going to the next one.

User Scenario 2:
* I'm wanting to get information at the Guideline-level, so I'm walking through the Guideline SCs.
* While looking at a guideline, I decide I want to look at the SCs.
* Then I go back to Guideline-level walking.

User Scenario 3:
* ...

> A link to the first SC (and all SCs within the Guideline) is available in the section just above

***If*** the prev/next stays at the bottom right under the list of SCs, then I think it'd be OK.

***Note***: For how I use the Understanding docs, I would want the prev/next at the top of the page (or maybe top and bottom)

<hr>

If we have time in EOWG telecon, how about do informal user research to:
1. get input on how EOWG folks use the Understanding docs and nav
2. encourage them to do that with others, and report back

**Comment by hidde** [comment]
Thanks for writing up these user scenarios, @slhenry! 

Sounds like a plan to ask EOWG folks about how they use it and ask others, just noticed you beat me to adding it to the agenda! :-) 

Do you know if there's precedent for the prev/next to appear at the top in other WAI pages? Use case makes sense to me…

**Comment by slhenry** [comment]
> Do you know if there's precedent for the prev/next to appear at the top in other WAI pages?

It's only at the bottom of pages now. (and only a few at that)

***and*** OK to precedent if there's a good reason to! :-)

**Comment by shawna-slh** [comment]
Looks like to me this is the latest proposal?

![image](https://user-images.githubusercontent.com/6991814/133334349-15a085f5-b660-4963-83ef-5b6c2b4042ff.png)

![image](https://user-images.githubusercontent.com/6991814/133333513-8c64d7bc-3cea-4eee-80fa-05e0c548a5e3.png)

That seems good to me. Or am I missing an open issue with it?

Not at top: I saw some draft with that control at the top (maybe COGA), and it was very ugly and distracting. If we were to do something at the top, would need different design. How about for now we leave it as is, and add a low priority issue for possible future enhancement to keep on the lookout for if users comment on missing the nav at the top & ideally doing some usability testing.

**Comment by hidde** [comment]
Cool, I am also happy with how we have it in the screenshot. These display at the bottom of the document.

Closing this!
