### ISSUE TITLE
In figcaptions, can we add space between figure ID and description?

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-supporting-documents-redesign#29]
Figcaptions are identified like “Figure 1”, but there is no space between its ID and the rest of its description: 

Example from a figure in the [current version of Understanding Text Spacing](https://www.w3.org/WAI/WCAG21/Understanding/text-spacing):

<img width="476" alt="Figure 1: vertical text cut off is a failure, with no space between '1' and 'vertical'" src="https://user-images.githubusercontent.com/178782/100729401-03324000-33c9-11eb-8ce6-25de5d4d9783.png">

* Is there a reason why this is the case?
* Can we technically (but automatically) add a space?
* Do we want to?

cc @slhenry @michael-n-cooper @nitedog

**Comment by slhenry** [comment]
> Do we want to?

Yes!

I think it should have **a period and a space after the period**, e.g.:
> Figure 1. Description

(I didn't spend time to confirm that in Style Guides, as I'm pretty confident that is common style.)

**Comment by michael-n-cooper** [comment]
The generator is supposed to be adding a space. I'll have to look at why that's not happening. If it should have a colon or full stop as well, we can add while I'm at it.

**Comment by hidde** [comment]
Thanks Shawn and Michael, colon or stop sound good. 

@michael-n-cooper I noticed there's a space in [`base.xslt:L154`](https://github.com/w3c/wcag/blob/master/xslt/base.xslt#L152), not sure why it is not rendered, thanks for helping out!

**Comment by hidde** [comment]
This was resolved, the space is now visible
