### ISSUE TITLE
Main Understanding and Techniques pages do not use a standard W3C document type style (Note, Rec, what is it?)

### ISSUE THREAD

**Issue by cookiecrook** [w3c/wai-wcag-supporting-documents-redesign#3]
Main Understanding and Techniques pages do not use a standard W3C document type style (Note, Rec, what is it?)

Among other things, there is no visible banner in the top left corner stating what type of document it is.

**Comment by hidde** [comment]
I think many find these documents through search engines, which may add to the confusion as there is less context compared to accessing via a W3C page.

We're considering (see https://github.com/w3c/wai-wcag-supporting-documents-redesign/issues/2) adopting the [WAI website](https://w3.org/WAI) / [WAI design components](https://wai-website-theme.netlify.app/components/) style, which has W3C logo and colors.

**Comment by hidde** [comment]
Closing this in favour of #2, where we'll further discuss what this would look like. Ensuring there is a visible banner for the type of document is one of the core parts of this project.
