### ISSUE TITLE
[strong] quote component for people quotes, not WCAG wording

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-wcag-supporting-documents-redesign#33]
The giant quote visual design communicates to me: THIS IS A QUOTE of something a PERSON said.

I think we want the quote design for the User Experience quotes.

For the SC wording, I think we want something more like a simple box.

**Comment by hidde** [comment]
Thanks for this, makes sense to me, I will make sure we don't use the giant quote for quoting WCAG wording. 

Maybe we can add this as guidance into the [Design Components](https://wai-website-theme.netlify.app/components/blockquotes/)?

**Comment by slhenry** [comment]
Well it said:
> For quoting someone.

;-)

I updated it to:
> The styles below are for quoting a person.
> We might develop other styles for quoting a document, e.g., WCAG excerpt.

**Comment by hidde** [comment]
Ooh, apologies, I read over that.

Your change does it it better, thanks!
