### ISSUE TITLE
[Understanding docs] Improve Success Criterion styling, don't use italic

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-supporting-documents-redesign#37]
Currently we display SC text in italics and indented, which is too much italic text especially for SCs with long text.
 
<img width="967" alt="" src="https://user-images.githubusercontent.com/178782/116210496-37751700-a743-11eb-800a-5144fcf7ff21.png">

Suggested: use a box, something like on https://www.w3.org/WAI/fundamentals/accessibility-intro/#making.

cc @shawna-slh

**Comment by shawna-slh** [comment]
Here is some more input. I will need to think about it before I have suggestions. :-)

Here are the different boxes we have: https://wai-website-theme.netlify.app/components/boxes/

In [What's New we use a gray box](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/#134-orientation-aa) for the SC text. Would be nice to be consistent.

The draft supporting doc design is currently using gray box for "About this page". And maybe we want the two boxes to be different? Or not? _(I need to think about it)_

Note that we can decide to change the box in What's New if there's a compelling reason to.

(um, and also that box needs to be added to the design components :-/)

**Comment by shawna-slh** [comment]
Hi @Hidde I'm pointing to your prototypes a lot.

For now, would you be comfortable matching the visual design of https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/ (and https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/) for:
* SC wording
* user quotes

Not that we have to stick with that, but seems good to have in place to consider and be consistent for now. :-)

**Comment by hidde** [comment]
Sure, will do that!

**Comment by shawna-slh** [comment]
CSS is here https://raw.githubusercontent.com/w3c/wai-intro-wcag/master/content/new-in-22.md

I am sure it can be improved!

(and, as I said above, once we settle on design, it should be added to the design components, and the What's New pages updated to use that :-)

**Comment by hidde** [comment]
Hm, I love how it looks on the “What's new in WCAG 2.2” page, but not really how it looks in the supporting docs lay-out, because there is a box on the right already, which looks slightly different (colors, shadow).

<img width="1313" alt="" src="https://user-images.githubusercontent.com/178782/118988515-8ba99a80-b981-11eb-9535-1d30eda5f6ae.png">

Suggestion:

* subtler box that is just a gray outline
* put non-essential SC content in 'show full description' expand/collapse, just like in QuickRef and redesigned WCAG EM Report Tool
* use less than full width and align right so that first heading is natural first item in the reading order

<img width="1313" alt="" src="https://user-images.githubusercontent.com/178782/118991492-155a6780-b984-11eb-84de-0799575bb476.png">

Do you have thoughts on this?

**Comment by hidde** [comment]
@shawna-slh ping, do you have comments on the proposal above? Thanks!

**Comment by shawna-slh** [comment]
Hi Hidde. Sorry for the delay.

I've wanted to look at it bigger picture - along with the design elements that we use throughout the WAI website (e.g., how we are using different boxes and shading for ***highlighting*** information versus ***side-noting*** information? are we doing it well? are we consistent? what do we want to change? how do we need to improve the documentation?) -- and that takes a bigger chunk of time and certain headspace, which I haven't been able to make so far. I will try hard to this week to get my UCD for UI and content design hats on!

For now I'll say:
* Looking at [What's New](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/) fresh, I don't like some aspects of the visual design. (I think I pulled it together kinda on the fly, and it definitely can be improved!)
* The user needs for the SC wording are very different between the Understanding docs and the report tools - nearly opposite actually. And thus we probably want different visual treatment for it.
   * For the Understanding docs, the user is wanting to learn more about the SC and what it means to them. Therefore, in the Understanding docs, I think the SC wording should be prominent.
   * For the Report tools, I hope most users know they SC text very well! So there, it can be less prominent.
* In the image above, to me the oddly indented SC box looks like a bug.

**Comment by shawna-slh** [comment]
Hi @hidde. Here is more clear suggestions based on my previous input, e.g.:

>For the Understanding docs, the user is wanting to learn more about the SC and what it means to them. Therefore, in the Understanding docs, I think the SC wording should be prominent.

* [ ] It seems important for users to see the the full description by default. (And not worth the clutter to add a button to hide it.)
* [ ] Please left align it.
* [ ] The "subtler box that is just a gray outline" seems fine.

**Comment by hidde** [comment]
Cool, let's do that!

**Comment by hidde** [comment]
Have implemented this, updated layout is now available in the preview for [Understanding documents](https://draft-wcag-redesign.netlify.app/understanding/)
