### ISSUE TITLE
Make “normative” explicit

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-supporting-documents-redesign#41]
Proposal: in the sidebars of supporting documents, add an explicit property stating whether the document is normative or not, for example “Normative” or “Required for conformance”. The value is “No” for all of our documents, but that may not be common knowledge.

Context: 
* AGWG committed to addressing unclarity around normativity of supporting documents https://github.com/w3c/wai-wcag-supporting-documents-redesign/issues/4
* address “indication of requiredness” point in our [Requirements Analysis](https://github.com/w3c/wai-wcag-supporting-documents-redesign/wiki/Requirements-Analysis#background)

Other ways we (could) address this, redundantly: 
* Optimise the one sentence description of what techniques are (“Examples of”), write it in a way that reinforces the idea that these are not the only way
* In the [WCAG 2 Documents](https://w3c.github.io/wai-wcag-supporting-documents-redesign/alt-index.html) page 
* listing “Type of Technique”, both “Advisory” and “Sufficient” hint in the direction that these are examples of ways, rather than the way

Open questions: 
* what's a good phrase?
* are there better ways to indicate requiredness?

cc @nitedog @shawna-slh 

<img width="322" alt="" src="https://user-images.githubusercontent.com/178782/116386128-c8b6bd00-a819-11eb-871c-9ccab2bb0d1a.png">

**Comment by hidde** [comment]
For context: 

current Techniques have a section “Important Information about Techniques” with text: 

> See Understanding Techniques for WCAG Success Criteria for important information about the usage of these informative techniques and how they relate to the normative WCAG 2.1 success criteria. The Applicability section explains the scope of the technique, and the presence of techniques for a specific technology does not imply that the technology can be used in all situations to create content that meets WCAG 2.1. 

This text also addresses the same need. However, automated readability testing services rate this text as academic / university professor level. My suspicion is we may confuse readers with this text. I would say replacing it with something like “Normative: no” or “Required for conformance: no” would make it much easier to understand the normativity/requiredness of the contents of this page.

**Comment by nitedog** [comment]
My vote goes to this combination:

1. Work on the "Techniques are examples of ..." sentence, to add clarity as needed
2. Keep the "Important Information about Techniques" paragraph -- yet maybe simplify it, move it down in the page, and/or make it expandable/collapsible (and collapsed by default because it is probably only used once by people new to WCAG)
3. Add something corresponding to the "About Techniques" page -- maybe more explanatory than the above paragraph?
4. Align these three pieces and cross-link them as needed (eg. sentence links to in-page paragraph, which links to the more explanatory section on the "About Techniques" page).

**Comment by hidde** [comment]
Sounds like a good combination of things! (Personally, I feel if we keep the paragraph, but rewritten, collapsed and towards the footer of the page, we may as well not have it?)

I really like explaining this on the About Techniques page, as this is information we want everyone to know, understand and easily find.

And hopefully the reword of “Techniques are examples of” sentence will help with this understanding too. I'm using “examples of ways to…” as opposed to “rules”/”norms”, but am open for other suggestions. Would like to keep it short and in  plain, non-academic language.

**Comment by hidde** [comment]
Discussed with @michael-n-cooper, @shawna-slh, @nitedog :

<img width="1051" alt="About this page section says They are not required to not meet WCAG" src="https://user-images.githubusercontent.com/178782/121205159-b9467d00-c877-11eb-9476-ab0696bccdb5.png">
