### ISSUE TITLE
Ensure prev/next component exists in WAI Design Components

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-supporting-documents-redesign#44]
These currently don't exist in WAI Design Components, but they are in the WAI CSS.

This issue is to ensure that we document both the regular one and the one with a header that shows what a prev/next belongs to (like 'Part of this guideline')

<img width="746" alt="previous next links to SCs with above a link to a guideline" src="https://user-images.githubusercontent.com/178782/126453208-78be8d15-762d-44f5-90e4-7c75801631df.png">

cc @SteveALee

**Comment by SteveALee** [comment]
I'll take a look at adding as a WAI Design Component when I add to the supplemental-guidance (was coga-design-guide)

**Comment by hidde** [comment]
@SteveALee Hey! I know you've added this in COGA, did  you also add to WAI Website Theme by  any chance? Or should I?

**Comment by SteveALee** [comment]
Yeah, it's called pager and is in my unmerged design guide branch.

But, as it stands it's coga specific and needs a little refactoring. The last part is the generic widget (there's a comment to that effect).

If it can wait 'till next week I can do it.

**Comment by hidde** [comment]
Thanks, that's great!

**Comment by SteveALee** [comment]
@hidde I think we decide this wasn't actually needed after all. But documentation is a bit hidden?

**Comment by hidde** [comment]
Ah yes, this is documented in [Front Matter, navigation section](https://wai-website-theme.netlify.app/writing/frontmatter/#navigation), closing this issue.
