### ISSUE TITLE
[low priority] Back to Top

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-supporting-documents-redesign#54]
main WAI website has "Back to Top"

Is there a reason not to have it for this template?

**Comment by hidde** [comment]
easy to add, and would be happy to do it, agree it could be useful on many of the pages.

**Comment by hidde** [comment]
Back to top is now working in latest [Techniques redesign draft](https://draft-wcag-redesign.netlify.app/techniques/aria/aria1)
