### ISSUE TITLE
Users want prev/next at the top of documents (as is currently)

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-supporting-documents-redesign#56]
We decided to only have prev/next at the bottom for our current set of documents. Maybe some users will want that at the top too and we might want to investigate that in the future?

context see @shawna-slh https://github.com/w3c/wai-wcag-supporting-documents-redesign/issues/28#issuecomment-919515891

**Comment by lakeen** [comment]
I vote for having prev/next nav at the top.

**Comment by carlosapaduarte** [comment]
I vote for having a way to reach similar resources in addition to the previous/next at the bottom. My favourite would be an expandable left side index with all the similar resources. But I'd also enjoy a (smaller) preview/next navigation at the top.

**Comment by daniel-montalvo** [comment]
+1 to small previous/next at the top.

**Comment by shawna-slh** [comment]
Addressed in latest design.
