### ISSUE TITLE
Add page contents box

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-supporting-documents-redesign#57]
Add page contents box if [plan for adding expand/collapse to headers](https://github.com/w3c/wai-wcag-supporting-documents-redesign/issues/49#issuecomment-920030489) does not work out.

Example on [Introduction to Web Accessibility](https://www.w3.org/WAI/fundamentals/accessibility-intro/): <img width="993" alt="heading introduction to web acessibility, underneath a page summary box with directly underneath a heading page contents with underneath that a list of links to sections on this page" src="https://user-images.githubusercontent.com/178782/135871283-10c5a76b-5a18-4b9c-b6b7-7ad3d7619bcc.png">

**Comment by iadawn** [comment]
+1

Is the idea to use the summary box pattern that is used elsewhere?

**Comment by hidde** [comment]
yes!

**Comment by hidde** [comment]
(updated the issue description with more context)

**Comment by shawna-slh** [comment]
From [carlosapaduarte comment in redundant issue](https://github.com/w3c/wai-wcag-supporting-documents-redesign/issues/63#issue-1006731609)

> I [would] miss [table of contents]. I find these resources to be long enough to warrant one. 

> In my role as ACT rule writer I often consult tests in techniques, and having the table of contents allows me to quickly navigate to the test section in the page instead of having to scroll to the bottom.

**Comment by shawna-slh** [comment]
Addressed in latest design.
