### ISSUE TITLE
"About this page" is not really about the page

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-wcag-supporting-documents-redesign#61]
The "About his page" box apparently serves two purposes: it has a short sentence about the general concept being presented in the page (understanding documents; techniques) and then details about the success criterion or about the technique. The latter seems to me to be the most relevant information of the two.

Suggestion: relabel it using the ID of the resource. For example, "About C6" (for CSS technique C6) or "About SC1.1.1"

**Comment by hidde** [comment]
> The "About his page" box apparently serves two purposes: it has a short sentence about the general concept being presented in the page (understanding documents; techniques) and then details about the success criterion or about the technique. 

Correct! 

> The latter seems to me to be the most relevant information of the two.
>
> Suggestion: relabel it using the ID of the resource. For example, "About C6" (for CSS technique C6) or "About SC1.1.1"

Both aspects are important, I believe. Users who are well-versed in the WCAG universe may already know what Techniques are and just need to know the specifics, but users who are not, they may have ended up on this page through a search engine or something, require general context, like that the document is part of a set, what that set is as compared to other sets, etc.

**Comment by carlosapaduarte** [comment]
> Both aspects are important, I believe. Users who are well-versed in the WCAG universe may already know what Techniques are and just need to know the specifics, but users who are not, they may have ended up on this page through a search engine or something, require general context, like that the document is part of a set, what that set is as compared to other sets, etc.

Agreed. If my message implied that I wanted to remove any content from the box then my apologies because that was not what I meant. I was just suggesting to update the label of the box to try to better communicate its purpose.

**Comment by hidde** [comment]
Ah, thanks for explaining, that makes sense! 

The reason it is “About this page” is that the heading can then be the same across all Techniques, and not just across Techniques, but also across Understanding docs and ACT Rules. This consistency within the set of documents and between the sets of documents, is meant to help users recognise that they've arrived at the same box they know from other (sets of) documents.

With that in mind, how do you feel about the naming?

**Comment by carlosapaduarte** [comment]
I agree that consistency is important. I would argue that visual consistency will be achieved by the same style and position of the box on all pages. But to ensure consistency in all circumstances we might have to rely on the label. So, I'm OK with keeping "About this page"

**Comment by hidde** [comment]
Thanks! In that case, let's keep it as is, will be closing this issue.
