### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-wcag-supporting-documents-redesign#63]
In https://github.com/w3c/wai-wcag-supporting-documents-redesign/issues/49#issuecomment-909269451 you mention no table of contents.

I will miss that. I find these resources to be long enough to warrant one. 

In my role as ACT rule writer I often consult tests in techniques, and having the table of contents allows me to quickly navigate to the test section in the page instead of having to scroll to the bottom.

**Comment by shawna-slh** [comment]
added to previous issue https://github.com/w3c/wai-wcag-supporting-documents-redesign/issues/57#issuecomment-972038001
