### ISSUE TITLE
Key terms

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-wcag-supporting-documents-redesign#64]
It is not clear to me what is the purpose of this section. (I couldn't find anything in the requirements analysis about it)
Is it to help understanding what the resource is about? If so, I don't think it does - check my comment below) 
Is it to help navigate between resources with the same key term? If so, then it might be better to label it as Related something (can't come up with a good name, sorry)
Is is to link to the glossary? If so, then why not label it Glossary?

It is also not clear what is the criteria for inclusion of key terms?
For example, in [SC1.1.1](https://draft-wcag-redesign.netlify.app/understanding/non-text-content) there is no key term "image" or "picture". I can't think of a more common non-text content so I would expect that to be a key term in SC1.1.1

**Comment by shawna-slh** [comment]
Addressed in latest design.
