### ISSUE TITLE
ACT page has “Date” and “Last modified” date, what do we want to do with those?

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-supporting-documents-redesign#74]
(this issue was created by request of brewerj)

**Comment by shawna-slh** [comment]
[WAI Resource template](https://raw.githubusercontent.com/w3c/wai-resource-template/master/content/index.md) has this as date in first line of the footer:
> <strong>Date:</strong> Updated @@ Month 2021. First published Month 20@@. [Changelog](@@).

or when first published:
> <strong>Date:</strong> Published @@ Month 2021.

For ACT Rules,
* [ ] I understand the changelog will be incorporated in the main body of the rule itself, which is fine and then we don't need changelog link in the footer.
* [ ] We previously said that "First published" is nice to have, but not a requirement. And hopefully that info is availability in the in-page changelog.
* [ ] Is there any reason not to use the WAI-site format and location for date updated? afaik, that is the "Last modified:" date in ACT Rules terms.

**Comment by shawna-slh** [comment]
Confirmed in 11 Jan meeting with @WilcoFiers @daniel-montalvo @SteveALee @brewerj  : Date in footer will be the last_modified. Will not have separate date elsewhere.
