### ISSUE TITLE
skip links

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-supporting-documents-redesign#81]
make visible on focus. top left.

**Comment by SteveALee** [comment]
Note that [Report tool](https://www.w3.org/WAI/eval/report-tool/) currenttly shows an extra line with translations etc. If this will appear in ALL minimal headers then skip links could go there.

**Comment by shawna-slh** [comment]
Good thought. Indeed Skip to Content link is there in the main WAI website.
> Skip to Content | Change Text Size or Colors | All Translations 

In the Report Tool, that extra line has only translations:.
> This page in: English , Nederlands | - Hide Translations

I think we do not want that extra line on minimal header pages unless there are translations.

We won't have translations of many of the resources with minimal headers, including the lists (of eval tools, courses, etc.).

So I think we do need another option for the minimal headers. We could:
* have it the same in all minimal headers, or,
* when there is a translation bar, put it there

I'm totally open to input on what would best meet user needs and expectations.

**Comment by SteveALee** [comment]
Seems to be only way to do skip link without extra line and to work with all responsive breakpoints - https://61dd9b453c13770008ca12c8--wai-wcag-supplemental.netlify.app/wcag-supplemental/all-supplemental-guidance/

**Comment by shawna-slh** [comment]
Thanks for investigating options!

I'm not keen on the main content jumping around. How about a big pop-up? OK if it overlaps some content. (I'll send examples"off-list".)

**Comment by SteveALee** [comment]
OK, the reason I switched to in inline from overlapped was that in some screen sizes the page title gets overlapped.

**Comment by shawna-slh** [comment]
Looks great in https://61df326736d192000783d920--wai-wcag-act-rules.netlify.app/standards-guidelines/act/rules/link-non-empty-accessible-name-c487ae/ !

/me will leave for Steve to close issue when it's implemented as he wants

**Comment by SteveALee** [comment]
@shawna-slh to be clear - this is ONLY in the new template - not the existing pages.
