### ISSUE TITLE
ACT test cases are not showing on WAI website

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wai-wcag-supporting-documents-redesign#86]
I want to include ACT test cases files in the WAI website. I've tried to do this by adding HTML files into the wcag-act-rules repository. Example: https://github.com/w3c/wcag-act-rules/blob/master/content/testcases/ff89c9/1acc47f25d4931c25fe3efbb676af6fd4e2ee57e.html which then should end up here: https://www.w3.org/WAI/standards-guidelines/act/rules/testcases/ff89c9/1acc47f25d4931c25fe3efbb676af6fd4e2ee57e.html

I previously noted these weren't showing up in the Netlify preview. Now that the site is live, I can now see this isn't (just?) a Netlify problem. I don't know enough about this system to figure out why this isn't working. What I understand from Jekyll documentation any file in the content directory without frontmatter will simply be passed on to the browser, so this really should work.

**Comment by SteveALee** [comment]
I think any files without front matter are not processed at all so do not end up in `_site`. There's another way to say add them, probably listing them in the config file, An empty front matter might work.

I'll check and get back ASAP.

**Comment by SteveALee** [comment]
They are there in Netlify but not where you want them to be as they end up n the same directory structure as the source, ie under `content...`. Eg

`/content/testcases/ff89c9/a582209de4a1d8ed76f54ca2e1f76d1efdbd499e.html`

The W3C hosting mapping does something with them but I cannot find them.

The `permalink` entry in the front matter specifies where the files end up , so you can either;

- Add front matter with permalink to every file :(
- make files a into a collection so you can assign a default permalink.

I did the latter in w3c/wcag-act-rules#83

It was ridiculously difficult to get working :(

**Comment by SteveALee** [comment]
Let me know your requirements and I'll see what I can do.

**Comment by SteveALee** [comment]
> This seems like a thing that should work

Totally agree. But Jekyll, and our architicture. :(

> Can you do further debugging to figure out why this isn't working?

After a thorough exploration I discovered that it IS working per Jekyll's limited options:

- files with no font matter get plonked in the same path under `_site ` - eg under `content`. That doesn't fit with our site architecture.
- all other site content files have fontmatter which either specifies the target URI path or causes the default in config to be used.
- no fontmatter - no correct URI path, except for collections
- collections are limited in other ways and so it appears not suitable for your requirements (as far as I know them)

Possible solutions I know at present are:

- manually add front matter to all files - could be empty allowing us to specific default in config (but again limited)
- use a build process to add frontmatter

Neither appear to fit your needs.

What about the glossary and implementations. do they work?

I will double check as I later discovered there's my view of `_site` was not getting updated after a build.

**Comment by WilcoFiers** [comment]
Thank you Steve. I think using content-assets can work.
